version: '3.1'

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=docker
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306

  api:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    command: npm start